### ISSUE TITLE
Coversion to Libre PC - AML-S905X-CC

### ISSUE THREAD

**Issue by SysInt17** [prueker/METARMap#42]
I have this project running currently on a Raspberry Pi 3B and everything works as expected.

Given the price and availability of Pi's these days, I found what appeared to be a near suitable replacement (Libre PC - M# **AML-S905X-CC**)  I picked up a couple of these from Amazon for $35/each.  Anyways, I was able to load Bullseye Lite and get follow most of the steps to recreate this project.  However, I can't figure out the GPIO Interface for the PWM Output and the "Overlays" I guess for the I2C for the small display.

Has anyone tried to get this project working on a Libre PC Le Potato?  This is my 2nd project building the Metar Map and wanted to gift it to my Flight Instructor since I recently became a Private Pilot.  

This is what I get when I try to run the project running on the AML-S905X-CC:

---------------------

metar@raspberrypi:~ $ python3 metar.py
Traceback (most recent call last):
  File "/home/metar/metar.py", line 6, in <module>
    import neopixel
  File "/usr/local/lib/python3.9/dist-packages/neopixel.py", line 18, in <module>
    from neopixel_write import neopixel_write
  File "/usr/local/lib/python3.9/dist-packages/neopixel_write.py", line 36, in <module>
    raise NotImplementedError("Board not supported")
NotImplementedError: Board not supported
metar@raspberrypi:~ $

**Comment by SysInt17** [comment]
Messing around with this for a few days and still haven't got it to work.  I did happen to find that my local MicroCenter had some of the Pi Zero W units in stock.  So I was able to pick one up, did a clean install and copied over my already working python3 project and bam, off to the races and working.  So yeah, for this project of 25 LED's, no big deal.
